# config.yml

#systemd run interval
systemd_timer: '6h'
#geoip-shell mode if set wrong script will fail
#valid inputs
# 'whitelist'
# 'blacklist'
blocking_mode: 
#Lists need no filtering or only '#' needs filtered
fetch_urls1:
  -  https://raw.githubusercontent.com/borestad/firehol-mirror/refs/heads/main/sslproxies_30d.ipset
  -  https://raw.githubusercontent.com/firehol/blocklist-ipsets/refs/heads/master/socks_proxy_30d.ipset
  -  https://raw.githubusercontent.com/firehol/blocklist-ipsets/refs/heads/master/botscout_30d.ipset
  -  https://raw.githubusercontent.com/ShadowWhisperer/IPs/refs/heads/master/Lists/Probes
  -  https://raw.githubusercontent.com/ShadowWhisperer/IPs/refs/heads/master/Lists/Scanners
  -  https://raw.githubusercontent.com/ShadowWhisperer/IPs/refs/heads/master/Lists/Tunnels
  -  https://raw.githubusercontent.com/Connie-Wild/scanner-ip-list/refs/heads/main/censys.txt
  -  https://raw.githubusercontent.com/Connie-Wild/scanner-ip-list/refs/heads/main/shodan.txt
  -  https://raw.githubusercontent.com/Connie-Wild/scanner-ip-list/refs/heads/main/openportstats.txt
  -  https://raw.githubusercontent.com/palinkas-jo-reggelt/List_of_Internet_Scanner_IPs/refs/heads/main/Scanner_IP_ranges.txt  
#unique formatting
#these need filtered to grab ips before country codes
fetch_urls2:
  -  https://raw.githubusercontent.com/stamparm/maltrail/refs/heads/master/trails/static/mass_scanner.txt