# config.yml

#systemd run interval
systemd_timer: '24h'
fetch_urls1:
  -  https://raw.githubusercontent.com/borestad/firehol-mirror/refs/heads/main/firehol_level1.netset
  -  https://raw.githubusercontent.com/borestad/firehol-mirror/refs/heads/main/firehol_level2.netset
  -  https://raw.githubusercontent.com/borestad/firehol-mirror/refs/heads/main/firehol_level3.netset
  -  https://raw.githubusercontent.com/borestad/firehol-mirror/refs/heads/main/firehol_level4.netset 
  -  https://raw.githubusercontent.com/borestad/iplists/refs/heads/main/spamhaus/spamhaus-drop.ipv4
  -  https://raw.githubusercontent.com/borestad/iplists/refs/heads/main/spamhaus/spamhaus-asndrop.ipv4
  -  https://raw.githubusercontent.com/borestad/firehol-mirror/refs/heads/main/et_block.netset
  -  https://raw.githubusercontent.com/Connie-Wild/scanner-ip-list/refs/heads/main/criminalip.txt
  -  https://raw.githubusercontent.com/Connie-Wild/scanner-ip-list/refs/heads/main/censys.txt
  -  https://raw.githubusercontent.com/Connie-Wild/scanner-ip-list/refs/heads/main/openportstats.txt
  -  https://raw.githubusercontent.com/Connie-Wild/scanner-ip-list/refs/heads/main/shodan.txt
  -  https://raw.githubusercontent.com/Connie-Wild/scanner-ip-list/refs/heads/main/shadowserver.txt
  -  https://raw.githubusercontent.com/Connie-Wild/scanner-ip-list/refs/heads/main/normshield.txt
  -  https://raw.githubusercontent.com/stamparm/ipsum/refs/heads/master/levels/2.txt
  -  https://raw.githubusercontent.com/borestad/firehol-mirror/refs/heads/main/firehol_abusers_1d.netset

fetch_urls2:
  -  https://raw.githubusercontent.com/borestad/blocklist-abuseipdb/refs/heads/main/abuseipdb-s100-3d.ipv4
  -  https://raw.githubusercontent.com/borestad/blocklist-abuseipdb/refs/heads/main/stats/hallofshame/subnets/abuseipdb-s99-hallofshame-30d-75percent.ipv4

  